#%RAML 1.0
title: WalletRecargas
version: v0
baseUri: http://api.walletgft.com

uses:
  _common: types/_common.raml
  provider: types/provider.raml
  bank: types/bank.raml

resourceTypes:
  collection: !include resourceTypes/collection.raml
  collection-item: !include resourceTypes/collection-item.raml

traits:
  searchable: !include traits/searchable.raml
  pageable: !include traits/pageable.raml
  sortable: !include traits/sortable.raml

/banks:
  type:
    collection:
      type: bank.bank
      collectionExample: !include examples/banks.json
      itemExample: !include examples/bank.json
  get:
    is: [pageable, sortable:{fieldsList: "name"}, searchable: {description: "with valid searchable fields: id, name", example: "[\"name\", \"Santan\", \"like\"]"}]

  /{bank-id}:
    type:
      collection-item:
        itemExample: !include examples/bank.json
        type: bank.bank
        updateExample: !include examples/bank.json
    uriParameters:
      bank-id:
        type: _common.id
        description: |
          Bank Identifier.


/providers:
  type:
    collection:
      type: bank.bank
      collectionExample: !include examples/providers.json
      itemExample: !include examples/provider.json
  get:
    is: [pageable, sortable:{fieldsList: "name"}, searchable: {description: "with valid searchable fields: id, name", example: "[\"name\", \"Santan\", \"like\"]"}]

  /{provider-id}:
    type:
      collection-item:
        type: provider.provider
        itemExample: !include examples/provider.json
        updateExample: !include examples/provider.json
    uriParameters:
      provider-id:
        type: _common.id
        description: |
          Provider identifier.
