#%RAML 1.0 Library

types:
  bank:
    type: object
    properties:
      id:
        type: integer
        minimum: 0
        description: |
          Bank Identifier.
        required: false
      name:
        type: string
        description: |
          Bank Name.
        required: true
